<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260120143032 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ranking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_80B839D0DB38439E ON ranking (usuario_id)');
        $this->addSql('CREATE TABLE ranking_pelicula (ranking_id INT NOT NULL, pelicula_id INT NOT NULL, PRIMARY KEY (ranking_id, pelicula_id))');
        $this->addSql('CREATE INDEX IDX_DED3298520F64684 ON ranking_pelicula (ranking_id)');
        $this->addSql('CREATE INDEX IDX_DED3298570713909 ON ranking_pelicula (pelicula_id)');
        $this->addSql('CREATE TABLE usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON usuario (email)');
        $this->addSql('CREATE TABLE valoracion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, puntuacion INT NOT NULL, comentario TEXT DEFAULT NULL, usuario_id INT NOT NULL, pelicula_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D3DE0F4DB38439E ON valoracion (usuario_id)');
        $this->addSql('CREATE INDEX IDX_6D3DE0F470713909 ON valoracion (pelicula_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D0DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ranking_pelicula ADD CONSTRAINT FK_DED3298520F64684 FOREIGN KEY (ranking_id) REFERENCES ranking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ranking_pelicula ADD CONSTRAINT FK_DED3298570713909 FOREIGN KEY (pelicula_id) REFERENCES pelicula (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE valoracion ADD CONSTRAINT FK_6D3DE0F4DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE valoracion ADD CONSTRAINT FK_6D3DE0F470713909 FOREIGN KEY (pelicula_id) REFERENCES pelicula (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ranking DROP CONSTRAINT FK_80B839D0DB38439E');
        $this->addSql('ALTER TABLE ranking_pelicula DROP CONSTRAINT FK_DED3298520F64684');
        $this->addSql('ALTER TABLE ranking_pelicula DROP CONSTRAINT FK_DED3298570713909');
        $this->addSql('ALTER TABLE valoracion DROP CONSTRAINT FK_6D3DE0F4DB38439E');
        $this->addSql('ALTER TABLE valoracion DROP CONSTRAINT FK_6D3DE0F470713909');
        $this->addSql('DROP TABLE ranking');
        $this->addSql('DROP TABLE ranking_pelicula');
        $this->addSql('DROP TABLE usuario');
        $this->addSql('DROP TABLE valoracion');
    }
}
